### ISSUE TITLE
Different environments for different executors?

### ISSUE THREAD

**Issue by TomNicholas** [cubed-dev/cubed-benchmarks#5]
Different executors have different dependencies, so we might want to run them in different CI environments.

We probably still want a single test fixture providing the `runtime`, but that perhaps should be parameterized at the level of different CI jobs (in a GH actions matrix).

**Comment by tomwhite** [comment]
We need different environments for different executors since the dependencies are so varied (and had conflicts in the past at least). 

We could have `environment-lithops-aws.yml`, etc, and then create the runtime objects according to what can be imported. So for Lithops AWS we'd try to `import lithops` and `import s3fs` and if that succeeded add the corresponding config file.

Perhaps there's a more elegant way of doing it though.

**Comment by tomwhite** [comment]
Fixed in #11
